# Generated by Django 5.2.9 on 2026-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
    ]
